from core.schemas import VehicleModelSeed


def build_discovery_prompt(seed: VehicleModelSeed, market='IL') -> str:
    return f"""JSON only. No prose. No markdown. No explanations outside JSON.\nReason max 120 chars. Evidence snippet max 220 chars. Max 2 snippets per source.\nResearch {seed.make} {seed.model} {seed.year_start}-{seed.year_end} for market {market}.\nReturn exactly top-level keys: {{\"search_queries\":[],\"sources\":[],\"candidate_variants\":[],\"conflicts\":[],\"unresolved\":false,\"unresolved_reason\":null}}\nAllowed statuses: verified, partial, conflict, unverified, unknown.\nForbidden statuses: inferred, assumed, likely, typical, common, estimated, guessed.\nIf no direct source: status=unknown, sources_count=0, used_in_compare=false, reason='No direct source.'\nCandidate variants must not be empty shells.\nEach candidate must include at least one of: engine, transmission, fuel_type, body_type, generation, year_start/year_end.\nIf no usable candidate facts are found, return candidate_variants=[] and unresolved=true.\nDo not return candidates with all critical fields null.\n"""


def build_verification_prompt(candidate_variants, sources) -> str:
    return """JSON only. No prose. No markdown. No explanations outside JSON.\nReason max 120 chars. Evidence snippet max 220 chars. Max 2 snippets per source.\nReturn exactly:\n{\"variant_verifications\":[{\"candidate_index\":0,\"field_verifications\":{\"body_type\":{},\"seats\":{},\"engine\":{},\"transmission\":{},\"fuel_type\":{},\"drivetrain\":{},\"generation\":{},\"year_start\":{},\"year_end\":{}},\"overall_status\":\"\",\"overall_confidence\":\"\",\"blocked_fields\":[],\"notes\":[]}]}\nAll critical fields must appear. If unknown output status=unknown.\nAllowed statuses only: verified, partial, conflict, unverified, unknown.\nForbidden: inferred, assumed, likely, typical, common, estimated, guessed.\n"""
